image: gafsel/java-postgres-build

pipelines:
  tags:
    calvinista-*:
      - step:
          script:
            - export DIR=$(pwd)
            - cd ..
            - git clone "https://$GAFS_BASE_GIT_USER:$GAFS_BASE_GIT_PASS@bitbucket.org/gafsel/gafs-base.git"
            - cd gafs-base
            - mvn clean install
            - cd ..
            - git clone "https://$PAGSEGURO_GIT_USER:$PAGSEGURO_GIT_PASS@bitbucket.org/gafsel/pagseguro.git"
            - cd pagseguro/source/pagseguro-api
            - mvn clean install
            - cd $DIR
            - git config --global user.name "$GIT_USER"
            - git config --global user.email "$GIT_EMAIL"
            - mvn clean package
            - apt-get update && apt-get install -y sshpass
            - sshpass -p "$DEPLOY_PASS" scp -o StrictHostKeyChecking=no app/target/calvinista-app.ear "$DEPLOY_USER@$DEPLOY_HOST":/tmp/
            - sshpass -p "$DEPLOY_PASS" ssh -o StrictHostKeyChecking=no "$DEPLOY_USER@$DEPLOY_HOST" '/opt/glassfish4/glassfish/bin/asadmin undeploy calvinista-app' || echo 'Não estava em execução'
            - sshpass -p "$DEPLOY_PASS" ssh -o StrictHostKeyChecking=no "$DEPLOY_USER@$DEPLOY_HOST" '/opt/glassfish4/glassfish/bin/asadmin deploy /tmp/calvinista-app.ear'
            - sshpass -p "$DEPLOY_PASS" ssh -o StrictHostKeyChecking=no "$DEPLOY_USER@$DEPLOY_HOST" 'rm /tmp/calvinista-app.ear' 