image: gafsel/java-postgres-build

pipelines:
  branches:
    release:
      - step:
        script: 
          - mvn clean package
          - git checkout master
          - git merge release
          - mvn release:prepare release:perform --batch-mode -Dusername=gafsel -Dpassword=discador01 -Darguments="-Dmaven.deploy.skip=true"